# Generated by Django 5.2.11 on 2026-05-21 08:06

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('memo', 'Official Institutional Memo'), ('news', 'Campus News Matrix Post'), ('announcement', 'Urgent Operational Registry Announcement')], default='memo', help_text='Determines which structural column feed this notice loads under.', max_length=20)),
                ('title', models.CharField(help_text='The main heading text displayed on the notice card wrapper.', max_length=255)),
                ('reference_number', models.CharField(blank=True, help_text='Optional catalog index parameter (e.g., TENP/EX/05/26), mostly used for internal memos.', max_length=100, null=True)),
                ('content', models.TextField(help_text='Main informational paragraph context block detailing the update payload.')),
                ('file_attachment', models.FileField(blank=True, help_text='Accepts document variants like PDFs or Docs for instant client download.', null=True, upload_to=Home.models.get_notice_file_path)),
                ('image', models.ImageField(blank=True, help_text='Dynamic graphic asset used uniquely within the news column layout matrix.', null=True, upload_to=Home.models.get_notice_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatic timestamp record entry used for downstream ordering arrays (-created_at).')),
            ],
            options={
                'verbose_name': 'Notice Board Entry',
                'verbose_name_plural': 'Notice Board Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The official company name of the technical attachment placement partner.', max_length=150, unique=True)),
                ('logo', models.ImageField(help_text='High-resolution brand asset mark (handled automatically with institutional CSS filters).', upload_to=Home.models.get_partner_logo_path)),
                ('website_url', models.URLField(blank=True, help_text='Optional hyperlink destination pointer for student placement inquiries.', null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Industry Partner',
                'verbose_name_plural': 'Industry Partners',
                'ordering': ['name'],
            },
        ),
    ]
