# Generated by Django 5.2.11 on 2026-06-24 08:05

import Home.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='category',
            field=models.CharField(choices=[('memo', 'Official Institutional Memo'), ('news', 'Campus News Matrix Post'), ('announcement', 'Urgent Operational Registry Announcement')], default='memo', max_length=20),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to=Home.models.get_notice_file_path),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Home.models.get_notice_image_path),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
