# Generated by Django 5.2.11 on 2026-06-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_noticeboard_expiry_date_noticeboard_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the research/innovation', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the research')),
                ('research_type', models.CharField(choices=[('project', 'Research Project'), ('publication', 'Publication'), ('innovation', 'Innovation'), ('collaboration', 'Collaboration'), ('conference', 'Conference')], default='project', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Main image for the research item', null=True, upload_to='research/images/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL (e.g., https://www.youtube.com/watch?v=...)', null=True)),
                ('document', models.FileField(blank=True, help_text='PDF or document file', null=True, upload_to='research/docs/')),
                ('researchers', models.CharField(blank=True, help_text='Names of researchers involved (comma separated)', max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, help_text='Year of publication/completion', null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('published', 'Published'), ('pending', 'Pending Review')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Research Item',
                'verbose_name_plural': 'Research Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
